## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: bionic
julia:
  - 1
notifications:
  email: false
git:
  depth: 99999999
sudo: required
addons:
  apt:
    update: true
    packages:
      - libgtk-3-dev
      - libavcodec-extra
      - python3-matplotlib
script:     
  - git clone https://github.com/JuliaRegistries/General  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "General"))')
  - git clone https://github.com/JuliaPOMDP/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "JuliaPOMDP"))')
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - travis_wait 30 julia --project --color=yes --check-bounds=yes -e 'import Pkg; Pkg.build("POMDPGallery"); Pkg.test("POMDPGallery", coverage=true)'

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("POMDPGallery"); Pkg.test("POMDPGallery"; coverage=true)'
# after_success:
#   # push coverage results to Coveralls
#   - julia -e 'cd(Pkg.dir("POMDPGallery")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#   # push coverage results to Codecov
#   - julia -e 'cd(Pkg.dir("POMDPGallery")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
